version: '3.3'
services:
  fluentd:
    build: ./fluentd
    # volumes:
    #   - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.11.2
    expose:
      - 9200
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    image: kibana:7.11.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"