version: '2.3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: unless-stopped
    mem_limit: 2g
    depends_on: 
      - elasticsearch


  elasticsearch:
    image: elasticsearch:7.11.2
    ports:
      - "127.0.0.1:9200:9200"
    environment: 
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      # - bootstrap.memory_lock=true 
    restart: unless-stopped
    mem_limit: 4g 


  kibana:
    image: kibana:7.11.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: unless-stopped
    mem_limit: 1g
    depends_on: 
      - elasticsearch